# Generated by Django 4.0.2 on 2022-02-05 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('link', models.URLField(max_length=700)),
                ('image', models.URLField(max_length=500)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
