# Generated by Django 4.0.2 on 2022-02-05 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('converter_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='title',
            field=models.CharField(default='null', max_length=500),
            preserve_default=False,
        ),
    ]
