# Generated by Django 4.0.3 on 2022-03-13 06:50

import converter_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('converter_app', '0003_alter_movies_image_alter_movies_link_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image_Compress',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=converter_app.models.file_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
