# Generated by Django 4.0.3 on 2022-03-26 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('converter_app', '0005_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='slug',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
