# Generated by Django 4.0.3 on 2022-03-26 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('converter_app', '0007_alter_task_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
